export const CHROME_MESSAGES = {
  TOGGLE_EXTENSION: 'TOGGLE_EXTENSION',
  RECEIVED_REQUEST: 'RECEIVED_REQUEST',
  REQUESTING_OPEN_STATUS: 'REQUESTING_OPEN_STATUS',
  ANSWERING_OPEN_STATUS: 'ANSWERING_OPEN_STATUS',
  REQUESTING_EXISTING_REQUESTS: 'REQUESTING_EXISTING_REQUESTS',
  ANSWERING_EXISTING_REQUESTS: 'ANSWERING_EXISTING_REQUESTS'
};
