module.exports = {
  CHROME_MESSAGES: {
    LAUNCH_OAUTH: 'LAUNCH_OAUTH',
    SEND_OVER_SCREENSHOTS: 'SEND_OVER_SCREENSHOTS',
    HERE_IS_YOUR_SCREENSHOT: 'HERE_IS_YOUR_SCREENSHOT',
    TOGGLE_EXTENSION: 'TOGGLE_EXTENSION',
    SEND_DATA_URI_TO_SLACK: 'SEND_DATA_URI_TO_SLACK',
    SLACK_ACCESS_TOKEN_UPDATE: 'SLACK_ACCESS_TOKEN_UPDATE'
  }
};
