export const CHROME_MESSAGES = {
  TOGGLE_EXTENSION: 'TOGGLE_EXTENSION',
  RECEIVED_HEADERS: 'RECEIVED_HEADERS',
  RECEIVED_REQUEST: 'RECEIVED_REQUEST',
  REQUESTING_TOGGLE_POSITION: 'REQUESTING_TOGGLE_POSITION'
};
